name: env-bug
description: Uncomment and modify the sections to configure your own amazing stack.
branding:
  icon: bell 
  color: blue 

inputs:
  - name: secret
    is-secret: true

configs:
  environments: 
    - name: staging
      parameters: 
        protected-branches: false
