name: env-bug
description: Uncomment and modify the sections to configure your own amazing stack.
branding:
  icon: bell # https://feathericons.com/
  color: blue # hex accepted

inputs:
  - name: secret
    is-secret: true

configs:
  environments: 
    - name: staging
      parameters: 
        protected-branches: false
        secrets:
          - name: SPN_ID
            value: ${{inputs.secret}}
